### ISSUE TITLE
Create AzureCore.framework iOS

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#136]
Contains all common infrastructure needed to process the request pipeline.

**Azure.Core**
- [x] Define HTTP Pipeline Architecture (@tjprescott, @bsiegel)
- [x] Implement HTTP Pipeline
  - [x] Implement basic HTTP Pipeline (@tjprescott)
  - [x] Pipeline configuration #150
  - [x] Implement request / response (de)serialization #147
  - [x] Error handling
  - [x] Cancellation #325
- [x] Implement HTTP Pipeline Policies
  - [x] Request modification
    - [x] User Agent #143
    - [x] Request ID #144
    - [x] Date #163
  - [x] Credentials
    - [x] Bearer token #146
  - [x] Response modification #161
    - [x]  Response validation
    - [x]  Scrub eTag
  - [ ] Retry #356
  - [x] Logging #149 (@bsiegel)
    - [x] Logger interface
    - [x] HTTP logger policy
    - [x] cURL-formatted logger policy
  - [x] ~Retry #145~
  - [x] ~Tracing #148~
  - [x] ~Proxy #154~
- [x] Define async architecture #152 (@tjprescott)
- [x] Define paging architecture #151 (@tjprescott)
- [x] Implement paging #164 (@tjprescott)
- [x] ~Define LRO architecture #153~
- [x] ~Implement LRO~

**Comment by tjprescott** [comment]
AzureCore has been released in Preview. Closing.
