### ISSUE TITLE
Create AzureIdentity.framework

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-ios#165]
Create an identity library with functionality comparable to the azure-identity library in other SDK languages, with only features that make sense for mobile.

- [ ] Determine if we'll make use of the MSAL library and, if so, how much of that will be required.
- [ ] Define which types of authentication are part of the scope for this effort. Tentatively:
    - OAuth2 (bearer token)
    - SAS Token
- [ ] Come up with public API proposal
- [ ] Implement proposed API including underlying private and protected models and classes
- [ ] Create unit and integration tests

**Comment by bsiegel** [comment]
Azure Identity was moved to "on hold" pending MSAL for iOS adding support for SwiftPM, which requires us & customers to be on Xcode 12 (GA expected in September). MSAL auth is not needed for Spool, and is low priority for Storage. Once MSAL team adds SwiftPM support we will treat as a target of opportunity.

Based on the above, I would remove this from the above milestones and add to the backlog.
