### ISSUE TITLE
AzureStorageBlob Transfer Manager

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-ios#166]
Create a transfer manager for blob storage. This includes significant architecture work to determine what functionality needs to be provided.

## Basic operations
- [x] Determine the range of the operations TransferManager will support: #217
  - track transfer progress
  - pause transfer
  - resume transfer
  - cancel transfer
  - get active transfers
- [x] Define how TransferManager will interface with the Storage Blob APIs #217
- [x] Define the mechanism by which TransferManager will re-auth and under what conditions it will do so #217
- [x] Implement download block #217
- [x] Implement upload block #216

## Persistence
- [x] Define how TransferManager will persist the operation queue across app runs #217
- [x] Implement blob transfer #216 #217
<del>- [ ] Implement multi-blob transfer #245</del>
