### ISSUE TITLE
EngSys for iOS Repository

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-ios#177]
We need to establish the baseline engineering system for the iOS repository. Looking at the capabilities of our other repos here are some of the capabilties/services that we need to get up and running.

- [x] Separate pipeline per service directory (e.g. ```sdk/[service]```)
- [x] Run build to validate that code compiles
- [x] Run tests (on agent or emulator?) against supported targets #343
- [x] Run analyze step with common steps and additional quality checks
- [ ] Setup release gates with approvals
- [x] ~~Automate release of pods~~
- [x] ~~Establish ```sdk/template``` for testing of pipeline and copy-paste.~~

**Comment by mitchdenny** [comment]
Closing this work item in favor of #532 which captures the specific remaining work around release.
