### ISSUE TITLE
Create AzureStorageBlob.framework iOS

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-ios#209]
Release checklist:
- [ ] Core #136
- [x] Identity MSAL #165
- [x] Pre-Authenticated URL provider #160
- [x] Storage upload #214
- [x] Storage download #140
- [x] Storage list #140
- [x] Storage delete #215
- [x] TM upload #216
- [x] TM download #217
- [x] TM Queue Management #166
- [x] TM Persistence #166
- [ ] ~TM Caching #166~ Not planned for preview 1.
- [ ] ~TM Aggregate Operations #166~ Not planned for preview 1.
- [ ] Resolve TODOs / lints #198
- [x] Public API review #210
- [ ] API docs #211
- [ ] Build system #177
- [ ] Release packaging #177
- [ ] Test coverage #212
- [ ] READMEs #190
- [x] UX study #213
- [ ] Blog post
- [ ] Storage error-body deserialization #162.
- [ ] BUG: Properties and Options cannot be Optional #243
- [ ] BUG: LocalURLs created from URLs provided by the OS can't be persisted #269
- [ ] Docs need Transfer Manager state diagram #294
- [ ] BUG: CoreData concurrency issues #307
- [ ] Arch board review #322
- [ ] Storage team review #323
- [ ] BUG: Saving context on app termination doesn't work #336
