### ISSUE TITLE
Improve docs for Core

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#372]
Consolidates work items that remain for AzureCore documentation.

- [ ] Add errors to docstrings. (see closed #288)
- [ ] Include simple and advanced examples (see closed #293)
- [ ] Ensure API docs for all public members. (see closed #211)
- [ ] Finalize AzureCore README.md (see closed #190)
- [ ] Publish final API docs (see closed #211)
