### ISSUE TITLE
AzureStorageBlob: Documentation

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#374]
Consolidates work items that remain for AzureStorageBlob documentation.

- [ ] Add errors to docstrings. (see closed #288)
- [ ] Include simple and advanced examples (see closed #293)
- [ ] Ensure API docs for all public members. (see closed #211)
- [ ] Finalize AzureStorageBlob README.md (see closed #190)
- [ ] Publish final API docs (see closed #211)
